In [1]:
my_list = [1,2,3]
s="10"
a=int(s)
print(type(a))

<class 'int'>


In [11]:
import numpy as np
x =np.array(my_list)
x.size

3

In [12]:
import numpy as np
x =np.array(my_list)
x.shape

(3,)

In [15]:
import numpy as np
x =np.array(my_list)
x.ndim

1

In [18]:
y=[[1,3],[5,2],[2,4]]
y=np.array(y)
print(y.ndim)
print(y.shape)
print(y.size)

2
(3, 2)
6


In [2]:
import numpy as np
np.arange(0,20,4)


array([ 0,  4,  8, 12, 16])

In [3]:
import numpy as np
np.arange(20,4)

array([], dtype=int32)

In [5]:
import numpy as np
np.arange(start=0,stop=20,step=4)

array([ 0,  4,  8, 12, 16])

In [18]:
import numpy as np
np.ones((4,2,3))

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [21]:
import numpy as np
np.ones((4,2,3))
print(np.ones((4,2,3)))

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


In [22]:
import numpy as np
np.zeros((4,2,3))

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [27]:
import numpy as np
np.linspace(2,4,5)

array([2. , 2.5, 3. , 3.5, 4. ])

In [28]:
import numpy as np
np.linspace(2,4,5,endpoint=False)

array([2. , 2.4, 2.8, 3.2, 3.6])

In [31]:
import numpy as np
np.linspace(2,4,3,retstep=True,endpoint=False)

(array([2.        , 2.66666667, 3.33333333]), 0.6666666666666666)

In [47]:
import numpy as np
np.eye(6,k=3)

array([[0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [46]:
import numpy as np
np.eye(6,k=-3)

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.]])

In [57]:
import numpy as np
np.random.rand(10)

array([0.25285202, 0.08197411, 0.0199915 , 0.65801352, 0.23578608,
       0.07968044, 0.78630146, 0.43496352, 0.42420559, 0.96463301])

In [238]:
import numpy as np
np.random.rand(2,3)

array([[0.75667808, 0.14035178, 0.33387803],
       [0.92812684, 0.56113337, 0.22861612]])

In [1]:
import numpy as np
np.random.rand(2,3,7)

array([[[0.7318227 , 0.13906908, 0.9966982 , 0.85131534, 0.06611243,
         0.94627698, 0.89511623],
        [0.76556636, 0.03927686, 0.21984557, 0.36926755, 0.70239206,
         0.90851932, 0.92968673],
        [0.63311862, 0.87098242, 0.33727812, 0.82148679, 0.38267175,
         0.15609669, 0.57043605]],

       [[0.46050971, 0.97515395, 0.03509512, 0.93142186, 0.13804779,
         0.10316209, 0.78969159],
        [0.41137832, 0.32023443, 0.00372199, 0.90023694, 0.23051462,
         0.9827368 , 0.59552011],
        [0.17069411, 0.87238195, 0.5783677 , 0.94601887, 0.52275358,
         0.05915315, 0.70995484]]])

In [114]:
import numpy as np
np.random.randn(5)

array([ 1.54645376, -1.38941725, -0.07382894,  0.32226723, -0.1773199 ])

In [232]:
import numpy as np
np.random.randn(2,3,2)

array([[[-0.03270499,  0.96956015],
        [ 0.30210803,  0.29209413],
        [-0.40186276,  0.29978551]],

       [[ 0.19225883, -0.98405804],
        [ 0.35746772,  1.73585233],
        [-0.14274201, -0.88135606]]])

In [185]:
import numpy as np
np.random.randint(10)

9

In [228]:
import numpy as np
np.random.randint(3,6,10)

array([5, 3, 5, 3, 3, 5, 3, 5, 4, 5])

In [10]:
import numpy as np
arr = np.arange(7)
print(arr)
print(arr.shape)
print(arr.reshape(7,1))

[0 1 2 3 4 5 6]
(7,)
[[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]]


In [119]:
import numpy as np
x=np.random.randint(3,6,10)
print(x)
print(x.max())
print(x.min())
print(x.argmax())
print(x.argmin())

[5 5 5 4 4 4 5 4 4 4]
5
4
0
3


In [122]:
import numpy as np
x=np.random.randint(3,6,10)
print(x)
print(x[3])
print(x[1:5])

[5 4 4 3 4 3 3 3 4 3]
3
[4 4 3 4]


In [128]:
import numpy as np
x=np.arange(0,7)
print(x)
print(x+x)
print(x-x)
print(x*x)

[0 1 2 3 4 5 6]
[ 0  2  4  6  8 10 12]
[0 0 0 0 0 0 0]
[ 0  1  4  9 16 25 36]
